### ISSUE TITLE
maven dependecy download

### ISSUE THREAD

**Issue by gyorb** [Ericsson/CodeCheckerEclipsePlugin#17]
Should we still use the mars release in maven to download the dependencies? http://download.eclipse.org/releases/mars

**Comment by dutow** [comment]
That depends on which eclipse platform we want to suggest.

The code doesn't depend on anything newish, last time I checked it even worked with Helios (3.6) - that was actually one of the original requirements. Instead of upgrading a more robust solution would be to make it configurable, and build it automatically against every supported eclipse platform version.

**Comment by gyorb** [comment]
the dependencies were updated together with the project setup changes.
