### ISSUE TITLE
Merge the bug path list into the Report List tree

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/CodeCheckerEclipsePlugin#22]
We do not need a separate window for the bug path list. Organize bug path list under report list similarly to how it is done in the CodeChecker web viewer.

**Comment by Locutus18** [comment]
I believe this has been partially done, please see https://github.com/Locutus18/CodeCheckerEclipsePlugin/tree/b8917e5437dd28800fd4dea9b2763a62a1ad2f01 and check it.

**Comment by dutow** [comment]
Yes, that looks like a good starting point for this.

Just a few ideas based on the diff of the latest commit:

 * Handle getChildren() specially for ReportInfo instances: always return true instead of checking the size of children, thus returning immediately. Depending on the child array basically prefetches every bugpath.
 * Implement partial tree refresh: currently the tree is totally reloaded (and closed) when we switch files. This is a highly annoying behavior if the bugpath is also in the same tree.
 * At least rename displayBugPath to something different. It doesn't reflect it's functionality anymore
 * I think displayBugPath also jumps to the source location of the problem

**Comment by Locutus18** [comment]
@dutow 
- Handle getChildren() specially for ReportInfo instances: always return true instead of checking the size of children, thus returning immediately. Depending on the child array basically prefetches every bugpath.

**Fixes**

- Implement partial tree refresh: currently the tree is totally reloaded (and closed) when we switch files. This is a highly annoying behavior if the bugpath is also in the same tree.

**Progress**

- At least rename displayBugPath to something different. It doesn't reflect it's functionality anymore. I think displayBugPath also jumps to the source location of the problem

**Viewer 1.1 : delete method because not longer used.**
