### ISSUE TITLE
after removing the log file it is never recreated

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/CodeCheckerEclipsePlugin#50]
If the codechecker log file is removed, it is never recreated.

**Comment by whisperity** [comment]
Are you sure? I have taken the following steps:

  1. Start Eclipse, do some work, do some checking, etc. Log files are present, written.
  2. Delete the log folder: `rm -r logs`
  3. Continue to do some work. Log files are **not** created &ndash; the Linux filesystem works this way, if you delete a file which is getting written to, the handle is still present but the output is like writing to `/dev/null`
  4. Totally restart Eclipse. The `logs` folder and a new file is created properly.

In which case do you wish the log file to be recreated or experience that it is not?

**Comment by dkrupp** [comment]
In my eclipse, neither the logs directory nor the files are recreated once they were removed. I removed them, when eclipse was not running. they are never recreated.

**Comment by whisperity** [comment]
It might be a third-party issue. Could you please do the following to test? (Needless to say these steps are **DESTRUCTIVE** to an already existing work environment!)

  1. Remove Eclipse, **completely**. This involves deleting the installed Eclipse release **and** the workspace(s).
  2. Remove the CodeChecker configuration files from CodeChecker-natured projects. Iterate every project which was given a CodeChecker nature and you will need to remove the following files: `.cproject`, `.project` and the `.settings` folder, recursively.
  3. Remove the directories `~/.p2` and `~/.m2` &ndash; these are where third-party dependencies are stored.
  4. Totally reinstall Eclipse, redownload and rebuild the plugin.

After that, it should be tested. On my and @Locutus18's computers this bug was seemingly never encountered.

**Comment by dkrupp** [comment]
logs directory is created in the current workdir where the eclipse executable is started.
instead create the logs directory in the actual workspace

**Comment by whisperity** [comment]
With this discovery, this issue is now related to #46.
